/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments/index'
import { Route as EmployeesListIndexRouteImport } from './routes/employees/list/index'
import { Route as EmployeesEmployeeIdIndexRouteImport } from './routes/employees/$employeeId/index'
import { Route as DepartmentsListIndexRouteImport } from './routes/departments/list/index'
import { Route as DepartmentsDepartmentIdIndexRouteImport } from './routes/departments/$departmentId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesListIndexRoute = EmployeesListIndexRouteImport.update({
  id: '/employees/list/',
  path: '/employees/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdIndexRoute =
  EmployeesEmployeeIdIndexRouteImport.update({
    id: '/employees/$employeeId/',
    path: '/employees/$employeeId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DepartmentsListIndexRoute = DepartmentsListIndexRouteImport.update({
  id: '/departments/list/',
  path: '/departments/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDepartmentIdIndexRoute =
  DepartmentsDepartmentIdIndexRouteImport.update({
    id: '/departments/$departmentId/',
    path: '/departments/$departmentId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/departments/$departmentId/': typeof DepartmentsDepartmentIdIndexRoute
  '/departments/list/': typeof DepartmentsListIndexRoute
  '/employees/$employeeId/': typeof EmployeesEmployeeIdIndexRoute
  '/employees/list/': typeof EmployeesListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdIndexRoute
  '/departments/list': typeof DepartmentsListIndexRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdIndexRoute
  '/employees/list': typeof EmployeesListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/departments/$departmentId/': typeof DepartmentsDepartmentIdIndexRoute
  '/departments/list/': typeof DepartmentsListIndexRoute
  '/employees/$employeeId/': typeof EmployeesEmployeeIdIndexRoute
  '/employees/list/': typeof EmployeesListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/departments/'
    | '/employees/'
    | '/departments/$departmentId/'
    | '/departments/list/'
    | '/employees/$employeeId/'
    | '/employees/list/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/departments'
    | '/employees'
    | '/departments/$departmentId'
    | '/departments/list'
    | '/employees/$employeeId'
    | '/employees/list'
  id:
    | '__root__'
    | '/'
    | '/departments/'
    | '/employees/'
    | '/departments/$departmentId/'
    | '/departments/list/'
    | '/employees/$employeeId/'
    | '/employees/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  DepartmentsDepartmentIdIndexRoute: typeof DepartmentsDepartmentIdIndexRoute
  DepartmentsListIndexRoute: typeof DepartmentsListIndexRoute
  EmployeesEmployeeIdIndexRoute: typeof EmployeesEmployeeIdIndexRoute
  EmployeesListIndexRoute: typeof EmployeesListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/list/': {
      id: '/employees/list/'
      path: '/employees/list'
      fullPath: '/employees/list/'
      preLoaderRoute: typeof EmployeesListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId/': {
      id: '/employees/$employeeId/'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId/'
      preLoaderRoute: typeof EmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/list/': {
      id: '/departments/list/'
      path: '/departments/list'
      fullPath: '/departments/list/'
      preLoaderRoute: typeof DepartmentsListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$departmentId/': {
      id: '/departments/$departmentId/'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId/'
      preLoaderRoute: typeof DepartmentsDepartmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  DepartmentsDepartmentIdIndexRoute: DepartmentsDepartmentIdIndexRoute,
  DepartmentsListIndexRoute: DepartmentsListIndexRoute,
  EmployeesEmployeeIdIndexRoute: EmployeesEmployeeIdIndexRoute,
  EmployeesListIndexRoute: EmployeesListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
