/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as R403IndexRouteImport } from './routes/403/index'
import { Route as ReportsSplatRouteImport } from './routes/reports/$'
import { Route as EmployeeSplatRouteImport } from './routes/employee_.$'
import { Route as SettingsChangePasswordIndexRouteImport } from './routes/settings/change-password/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403IndexRoute = R403IndexRouteImport.update({
  id: '/403/',
  path: '/403/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSplatRoute = ReportsSplatRouteImport.update({
  id: '/reports/$',
  path: '/reports/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSplatRoute = EmployeeSplatRouteImport.update({
  id: '/employee_/$',
  path: '/employee/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsChangePasswordIndexRoute =
  SettingsChangePasswordIndexRouteImport.update({
    id: '/settings/change-password/',
    path: '/settings/change-password/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/employee/$': typeof EmployeeSplatRoute
  '/reports/$': typeof ReportsSplatRoute
  '/403/': typeof R403IndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/change-password/': typeof SettingsChangePasswordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/employee/$': typeof EmployeeSplatRoute
  '/reports/$': typeof ReportsSplatRoute
  '/403': typeof R403IndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/change-password': typeof SettingsChangePasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/employee_/$': typeof EmployeeSplatRoute
  '/reports/$': typeof ReportsSplatRoute
  '/403/': typeof R403IndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/change-password/': typeof SettingsChangePasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/employee/$'
    | '/reports/$'
    | '/403/'
    | '/settings/'
    | '/settings/change-password/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/employee/$'
    | '/reports/$'
    | '/403'
    | '/settings'
    | '/settings/change-password'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/employee_/$'
    | '/reports/$'
    | '/403/'
    | '/settings/'
    | '/settings/change-password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRoute
  EmployeeSplatRoute: typeof EmployeeSplatRoute
  ReportsSplatRoute: typeof ReportsSplatRoute
  R403IndexRoute: typeof R403IndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsChangePasswordIndexRoute: typeof SettingsChangePasswordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403/': {
      id: '/403/'
      path: '/403'
      fullPath: '/403/'
      preLoaderRoute: typeof R403IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$': {
      id: '/reports/$'
      path: '/reports/$'
      fullPath: '/reports/$'
      preLoaderRoute: typeof ReportsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee_/$': {
      id: '/employee_/$'
      path: '/employee/$'
      fullPath: '/employee/$'
      preLoaderRoute: typeof EmployeeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/change-password/': {
      id: '/settings/change-password/'
      path: '/settings/change-password'
      fullPath: '/settings/change-password/'
      preLoaderRoute: typeof SettingsChangePasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  EmployeeSplatRoute: EmployeeSplatRoute,
  ReportsSplatRoute: ReportsSplatRoute,
  R403IndexRoute: R403IndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsChangePasswordIndexRoute: SettingsChangePasswordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
